import { Injectable } from '@nestjs/common';
import * as PDFDocument from 'pdfkit';

@Injectable()
export class PdfExportService {
  async generateReportPdf(
    reportType: string,
    reportData: any,
    options?: {
      title?: string;
      logo?: string;
      companyName?: string;
    }
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const title = options?.title || 'BaseMap Report';
      const companyName = options?.companyName || 'BaseMap';

      doc.fontSize(20).fillColor('#1e40af').text(title, { align: 'center' });
      doc.moveDown();
      doc.fontSize(10).fillColor('#666').text(`Generated by ${companyName}`, { align: 'center' });
      doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.moveDown(2);

      switch (reportType) {
        case 'landscape':
          this.renderLandscapeReport(doc, reportData);
          break;
        case 'capability-coverage':
          this.renderCapabilityCoverageReport(doc, reportData);
          break;
        case 'it-cost':
          this.renderItCostReport(doc, reportData);
          break;
        case 'eol-risk':
          this.renderEolRiskReport(doc, reportData);
          break;
        default:
          doc.fontSize(12).text('Report data not available');
      }

      doc.moveDown(2);
      doc.fontSize(8).fillColor('#999').text('Generated by BaseMap EAM Tool', { align: 'center' });

      doc.end();
    });
  }

  private renderLandscapeReport(doc: PDFDocument.PDFDocument, data: any) {
    if (data.summary) {
      doc.fontSize(14).fillColor('#1e40af').text('Summary', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#000');

      const summaryData = [
        ['Total Applications', data.summary.total?.toString() || '0'],
        ['Active', data.summary.byLifecycle?.Active?.toString() || '0'],
        ['Planning', data.summary.byLifecycle?.Planning?.toString() || '0'],
        ['Maintenance', data.summary.byLifecycle?.Maintenance?.toString() || '0'],
        ['Retirement', data.summary.byLifecycle?.Retirement?.toString() || '0'],
      ];

      summaryData.forEach(([label, value]) => {
        doc.text(`${label}: ${value}`, { continued: false });
      });
    }

    doc.moveDown();
    doc.fontSize(14).fillColor('#1e40af').text('Application List', { underline: true });
    doc.moveDown(0.5);

    if (data.applications?.length > 0) {
      const tableTop = doc.y;
      const colWidths = [150, 80, 80, 60, 60];
      const headers = ['Name', 'Lifecycle', 'Risk', 'BU', 'Owner'];

      doc.fontSize(9).fillColor('#fff');
      doc.rect(50, tableTop, 500, 20).fill('#1e40af');
      doc.fillColor('#fff').text('Name', 55, tableTop + 5, { width: colWidths[0] });
      doc.text('Lifecycle', 55 + colWidths[0], tableTop + 5, { width: colWidths[1] });
      doc.text('Risk', 55 + colWidths[0] + colWidths[1], tableTop + 5, { width: colWidths[2] });
      doc.text('BU', 55 + colWidths[0] + colWidths[1] + colWidths[2], tableTop + 5, { width: colWidths[3] });
      doc.text('Owner', 55 + colWidths[0] + colWidths[1] + colWidths[2] + colWidths[3], tableTop + 5, { width: colWidths[4] });

      doc.y = tableTop + 25;
      doc.fontSize(8).fillColor('#000');

      data.applications.slice(0, 30).forEach((app: any, index: number) => {
        if (doc.y > 700) {
          doc.addPage();
          doc.y = 50;
        }

        const rowColor = index % 2 === 0 ? '#fff' : '#f3f4f6';
        doc.rect(50, doc.y - 2, 500, 14).fill(rowColor);

        doc.text(app.name?.substring(0, 25) || '-', 55, doc.y, { width: colWidths[0] });
        doc.text(app.lifecycle || '-', 55 + colWidths[0], doc.y, { width: colWidths[1] });
        doc.text(app.risk_score?.toString() || '0', 55 + colWidths[0] + colWidths[1], doc.y, { width: colWidths[2] });
        doc.text(app.business_unit?.substring(0, 10) || '-', 55 + colWidths[0] + colWidths[1] + colWidths[2], doc.y, { width: colWidths[3] });
        doc.text(app.owner?.substring(0, 10) || '-', 55 + colWidths[0] + colWidths[1] + colWidths[2] + colWidths[3], doc.y, { width: colWidths[4] });

        doc.y += 14;
      });
    }
  }

  private renderCapabilityCoverageReport(doc: PDFDocument.PDFDocument, data: any) {
    if (data.summary) {
      doc.fontSize(14).fillColor('#1e40af').text('Coverage Summary', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#000');

      doc.text(`Total Capabilities: ${data.summary.total_capabilities || 0}`);
      doc.text(`Covered: ${data.summary.covered || 0}`);
      doc.text(`Partial Coverage: ${data.summary.partial || 0}`);
      doc.text(`Gaps: ${data.summary.gaps || 0}`);
      doc.moveDown();
    }

    if (data.capabilities?.length > 0) {
      doc.fontSize(14).fillColor('#1e40af').text('Capability Details', { underline: true });
      doc.moveDown(0.5);

      doc.fontSize(9).fillColor('#000');
      data.capabilities.slice(0, 25).forEach((cap: any) => {
        const statusText = cap.status === 'gap' ? '🔴 GAP' : cap.status === 'partial' ? '🟡 PARTIAL' : '🟢 COVERED';
        doc.text(`${statusText} ${cap.name} (Level ${cap.level}) - ${cap.total_applications} apps - ${cap.coverage_percent}% coverage`);
        doc.moveDown(0.3);
      });
    }
  }

  private renderItCostReport(doc: PDFDocument.PDFDocument, data: any) {
    if (data.summary) {
      doc.fontSize(14).fillColor('#1e40af').text('Cost Summary', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#000');

      doc.text(`Total Cost: $${(data.summary.total_cost || 0).toLocaleString()}`);
      doc.text(`Applications: ${data.summary.application_count || 0}`);
      doc.text(`Average Cost per App: $${Math.round(data.summary.average_cost_per_app || 0).toLocaleString()}`);
      doc.moveDown();
    }

    if (data.cost_by_type) {
      doc.fontSize(14).fillColor('#1e40af').text('Cost by Type', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#000');

      Object.entries(data.cost_by_type).forEach(([type, amount]: [string, any]) => {
        doc.text(`${type}: $${Number(amount).toLocaleString()}`);
      });
    }

    if (data.top_expensive_applications?.length > 0) {
      doc.moveDown();
      doc.fontSize(14).fillColor('#1e40af').text('Top 10 Expensive Applications', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#000');

      data.top_expensive_applications.forEach((app: any, index: number) => {
        doc.text(`${index + 1}. ${app.name}: $${app.cost.toLocaleString()}`);
      });
    }
  }

  private renderEolRiskReport(doc: PDFDocument.PDFDocument, data: any) {
    if (data.summary) {
      doc.fontSize(14).fillColor('#1e40af').text('EOL Risk Summary', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor('#000');

      doc.text(`Critical (<30 days): ${data.summary.critical || 0}`, { color: '#dc2626' });
      doc.text(`High (<90 days): ${data.summary.high || 0}`, { color: '#ea580c' });
      doc.text(`Medium (<180 days): ${data.summary.medium || 0}`, { color: '#ca8a04' });
      doc.text(`Low (>180 days): ${data.summary.low || 0}`, { color: '#16a34a' });
      doc.text(`Past EOL: ${data.summary.past_eol || 0}`, { color: '#6b7280' });
      doc.moveDown();
    }

    if (data.risks?.critical?.length > 0) {
      doc.fontSize(14).fillColor('#dc2626').text('Critical EOL Risks', { underline: true });
      doc.moveDown(0.5);

      doc.fontSize(9).fillColor('#000');
      data.risks.critical.slice(0, 15).forEach((app: any) => {
        doc.text(`⚠️ ${app.name} - ${app.vendor || '-'} - EOL: ${new Date(app.eol_date).toLocaleDateString()} (${app.days_until_eol} days)`);
        doc.moveDown(0.3);
      });
    }
  }
}